management:
  security:
    enabled: false
  context-path: /actuator

spring:
  application:
    name: eureka-server
server:
  port: 9100

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
